import { ColumnType } from "types";

export const columns: ColumnType[] = [
  {
    key: 1,
    label: "ID",
    path: "id"
  },
  {
    key: 2,
    label: "Generated By",
    path: "generated_by"
  },
  {
    key: 3,
    label: "Date Created",
    path: "date_created"
  },
  {
    key: 4,
    label: "Status",
    path: "status"
  }
];
