import { AxiosResponse } from "axios";
import moment from "moment";
import { ColumnType } from "types";
import { currencyFormat } from "utils/currencyFormat";

export const columns: ColumnType[] = [
  {
    key: 1,
    label: "ID",
    path: "id"
  },
  {
    key: 2,
    label: "Generated By",
    path: "generated_by"
  },
  {
    key: 3,
    label: "Date Created",
    path: "date_created"
  },
  {
    key: 4,
    label: "Status",
    path: "status"
  }
];

export const parseBatchPayoutList = (
  response: AxiosResponse<any, any> | undefined
) => {
  return response?.data?.data.map((batch: any) => ({
    date_created: moment(batch.createdAt).format("LL"),
    generated_by: `${batch?.user?.first_name} ${batch?.user?.last_name}`,
    id: batch.id,
    status: batch.status
  }));
};

export const parseAgentPayout = (
  response: AxiosResponse<any, any> | undefined
) => {
  return response?.data?.payout?.agent_payouts.map((agent_payout: any) => ({
    admin_fee: currencyFormat(agent_payout?.admin_fee),
    game_code: agent_payout?.agent?.game_code,
    id: agent_payout.id,
    initial_salary: currencyFormat(agent_payout?.initial_salary),
    name: `${agent_payout?.agent?.first_name} ${agent_payout?.agent?.last_name}`,
    status: agent_payout?.status,
    sub_agent_salary: currencyFormat(agent_payout?.sub_agent_salary),
    total_salary: currencyFormat(agent_payout?.total_salary)
  }));
};
